### ISSUE TITLE
Dcoumentation Issue: Package name mentioned wrong for Uninstall Process 

### ISSUE THREAD

**Issue by cchib** [hpe-storage/python-3parclient#24]
Uninstalling an old client : If the older HP3PARClient was installed on the system already it will need to be removed. Run the following command to remove it:
$ sudo pip uninstall hp3parclient

The correct package name
$ sudo pip uninstall python-3parclient

**Comment by aorourkehp** [comment]
python-3parclient is the name of the new package.

hp3parclient is the old package name (https://pypi.python.org/pypi/hp3parclient) which should be removed before installing the new python-3parclient.

**Comment by WaltHP** [comment]
aorourkehp is correct.  This is an invalid bug.
