### ISSUE TITLE
Snapshot promotion

### ISSUE THREAD

**Issue by Ganneff** [hpe-storage/python-3parclient#31]
Hi

i might be dumb, but I cant find a way to promote a snapshot using this API.  I can do it manually in the web interface of the 3par, but I miss the automation here.

Is it a missing function in the API, or did I overlook something?

Greetings
 Joerg

**Comment by wdurairaj** [comment]
Hi Joerg,

There is no direct way of promoting a snapshot to a volume. But you can do a physical copy of the snapshot and use the target volume of the physical copy as a workaround.

**Comment by Ganneff** [comment]
Hi

uh, do you mean "copyVolume" to a new one, then remove the old (of which i made a snapshot) and rename that new volume to the name of the old? And somehow magically keep all exports and stuff?
(It does seem to be that copyvolume wouldnt allow me to overwrite an existant one, though I havent tested that yet)

Or what do i miss?

**Comment by Ganneff** [comment]
Hi

oh, i just found that the latest master contains a "promoteVirtualCopy" function, which seems to do what I want. Going to test that, but if it does: Thanks to the coder! :)

Greetings, Joerg

**Comment by nilangekarss** [comment]
Hi Joerg,
We have recently added support for reverting volume to snapshot state. If you have a volume v1 and its snapshot s1 , you can revert the volume v1 state to s1 using "promote virtual copy".

**Comment by Ganneff** [comment]
Hi

yeah, as i wrote, its there now. And I just tested it, it does work, so yay, closing this.

Joerg
