### ISSUE TITLE
INT_SERV_ERR 1 500 returned  when using getVolumes() API call

### ISSUE THREAD

**Issue by JanosPesti** [hpe-storage/python-3parclient#61]
Hi,
we have a python script that pulls volume capacity information from the 3Par arrays to be stored in InfluxDB. The script worked fine with the old hp3parclient on our 3par 7400s and 8450 until the 3par 8450 was upgraded to 3.3.1.460 (MU3)+P50  . 
If I ran the script now, it returns values up until a point where it give this response:
Unable to get volume capacity
Internal Server Error (HTTP 500) 1 - internal server error

the actual call that fails (values in <> not shown for privacyreasons):
REQ: curl -i http://<arrayname>:8008/api/v1/volumes -X GET -H "Accept: application/json" -H "X-Hp3Par-Wsapi-Sessionkey: <sessionkey>" -H "User-Agent: python-3parclient"

Anyone encountered this? Anything changed in that OS version that changes API behavior?

**Comment by wdurairaj** [comment]
Above curl call will fetch all the volumes from the 3PAR. Do you have a data on the number of volumes on the 3PAR which failed ? Based on this information i can experiment in our lab setup

If you share some logs of working / non-working setup via email to me (william.dur.sandanaraj@hpe.com).. i can further analyse.

**Comment by JanosPesti** [comment]
when I ran the script, it returned 372 volumes and failed at that point.
But after the upgrade I see some SQLite errors in the activity log on the array as well, that may be connected.

**Comment by JanosPesti** [comment]
this was resolved, there is a bug in the 3par code that crashes when querying volumes and there is no rcopy license on the array. we applied a temp license and the script started to pull data again from the array.
