### ISSUE TITLE
Application set addition to the Volume

### ISSUE THREAD

**Issue by sidrockzz** [hpe-storage/python-3parclient#86]
There is no application set adding for the volume in the python-3parclient. Any idea how to do the task in python?

**Comment by traghavendra** [comment]
Hi sidrockzz,

Raghavendra here.
I didn't understand your question.

Can you please give some background? What is scenario you are trying?
What is expectation from python-3parclient?
Request you to please elaborate.

Thanks.

**Comment by sidrockzz** [comment]
I am working on adding the application set to the volume which I have created using the createVolume method available in the  python-3parclient, the thing is I am unable to add the application set to the volume via the module.
